---
title: "R Notebook"
output: html_notebook
---

<!--
# Arp3 / MRLC / F-actin soma-patch colocalization (consolidator)

## What this file does

Reads per-cell line-profile correlation tables for the three pairwise
combinations (actin-Arp3, Arp3-MRLC, actin-MRLC) at the soma (`csv_list` from
`Path_1`, lines 43, 53), pools them into a long-form table, and produces the
joint violin plot for ED Fig 6 soma colocalization (`ggsave` at line 153).

## Manuscript panel

**ED Fig 6d**: "Colocalization of indicated proteins at the soma. N = 82
neurons from 4 independent experiments. ***p < 0.001; ns, p >= 0.05 by
Two-tailed paired Wilcoxon test with Holm correction."

Source Data: `ED Fig 6 soma coloc`.

## Outputs

- One violin-plot PDF (`ggsave` at line 153).

## Original G:\ source

G:/Figure S6_myosin/Arp3_MLC_coloc/soma/read_stat.Rmd
(`read_stat.Rmd` is a known misnomer: this instance is the Arp3/MRLC soma
coloc analysis, not the Western-blot variant.)
-->

```{r message=FALSE}
library(pracma)
library(peakPick)
library(quantmod)
library(ggpmisc)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggfortify)
library(forecast)
library(tsibble)
library(broom)
library(tidyquant)
library(tsbox)
library("pheatmap")
library("RColorBrewer")
library(ggpmisc)
library(ggfortify)
library(viridis) # Default Color Maps from 'matplotlib' 
library(hrbrthemes)
library(data.table)
library(ggpubr)
library(superheat)
library(fs)
```
## load existing/saved environment (.RData)
```{r}
Path_1 <- dirname(rstudioapi::getSourceEditorContext()$path)
saved_path <- paste(Path_1, "df_list.RData",  sep = "/")
load(file=saved_path)

```

```{r message=FALSE}
csv_list<- list.files(Path_1,
                      pattern = "(.*)csv$",
                     recursive = TRUE,  #list of subfolders and files within the subfolders
                     include.dirs = F, # Should subdirectory names be included 
                     full.name = T)  #get the full name (path and file name) of each file

df_list<- list()

for (n in 1:length(csv_list)) 
{
  df_list[[n]] <- readr::read_delim(csv_list[n], ",", escape_double = FALSE, col_names = T, trim_ws = TRUE)
  df_list[[n]] <- df_list[[n]] %>% as.data.frame()
 
}


```


```{r message=FALSE}
df_1 <- df_list[[1]]


for (n in 2:length(df_list)) 
{
  df_1 <- rbind (df_1, df_list[[n]])
}

df_1$file<- path_file(csv_list)
df_1$pair<-path_dir(csv_list) %>% path_dir() %>% basename()
df_1$img<-gsub("\\_C.*","",path_file(csv_list))

names(df_1)[2:3] <- c("TOS_linear", "TOS_log2")
```


```{r message=FALSE}
df_1 %>% subset(df_1$pair == "Arp3_MLC") %>% subset(df_1$PCC < 0.2)

removed <- pos_1_long %>% subset(pos_1_long$Time == 1000)  %>% subset(value> 2000)
removed_cell<- removed$Cell
pos_1_long_removed<- pos_1_long[grep(paste(removed_cell,collapse="|"), pos_1_long$Cell , invert=TRUE) ,]


```


```{r}
Path_1 <- dirname(rstudioapi::getSourceEditorContext()$path)
saved_path <- paste(Path_1, "df_list.RData",  sep = "/")
save.image(file=saved_path)

saveRDS(df_1, file = "soma_coloc.rds")

```


```{r  message = FALSE, warning=FALSE, fig.width=10}

df_summary <- df_1 %>% group_by(pair) %>% rstatix::get_summary_stats()
```


```{r}

graph_list<- list()

graph_list[[1]]<- ggplot(df_1, aes(x= pair, y=PCC, fill=pair)) 
graph_list[[2]]<- ggplot(df_1, aes(x=pair, y=SRCC, fill=pair)) 
graph_list[[3]]<- ggplot(df_1, aes(x= pair, y=ICQ, fill=pair))
graph_list[[4]]<- ggplot(df_1, aes(x= pair, y=M1, fill=pair))
graph_list[[5]]<- ggplot(df_1, aes(x= pair, y=M2, fill=pair))
graph_list[[6]]<- ggplot(df_1, aes(x= pair, y=TOS_linear, fill=pair))
graph_list[[7]]<- ggplot(df_1, aes(x= pair, y=TOS_log2, fill=pair))


```


```{r, fig.width=10, echo=FALSE}


my_comparisons <- list(c("Arp3_actin", "Arp3_MLC"),c("Arp3_actin", "MLC_actin"), c("Arp3_MLC", "MLC_actin"))


graph_list[[2]]+
  geom_violin(trim=T,  bw=1, kernel ="gaussian", adjust=0.05)+
  
  #geom_point(aes(fill=pair), position = position_dodge(0.5))+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1, binwidth = 0.1)+ 
  geom_boxplot(width=0.1, fill="white")+ 
   scale_y_continuous(expand = c(0, 0), limits = c(-0.5 ,1.5), breaks = scales::pretty_breaks(n = 5)) + 
  
  #stat_summary(fun.data=data_summary)+ 
 stat_compare_means(comparisons = my_comparisons, method="wilcox.test")+
  
  theme_ipsum(grid = F, ticks = T) +
  theme_linedraw()+
   theme(plot.title = element_text(hjust = 0.5), 
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = "right",
        axis.text=element_text(size=12, face="bold")) #for centering the text 

```


```{r}
ggsave(
  "SRCC.pdf",
  plot = last_plot(),
  device = "pdf")
```
